# Configure main menu and social menu

[[main]]
identifier = "home"
name = "主页"
url = "/"
weight = -100

[main.params]
icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/xfqwdsj"

[social.params]
icon = "brand-github"
